package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
)

func main() {
	source := filepath.Join("..", "..", ".agents", "skills", "peer-context")
	paths := []string{
		"SKILL.md",
		"agents/openai.yaml",
		"references/cli-contract.md",
		"references/error-handling.md",
		"references/request-patterns.md",
	}
	sort.Strings(paths)
	output := "// Code generated by go generate; DO NOT EDIT.\n\npackage skillbundle\n\nvar generatedFiles = map[string]string{\n"
	for _, path := range paths {
		content, err := os.ReadFile(filepath.Join(source, filepath.FromSlash(path)))
		if err != nil {
			panic(err)
		}
		output += fmt.Sprintf("\t%s: %s,\n", strconv.Quote(path), strconv.Quote(string(content)))
	}
	output += "}\n"
	if err := os.WriteFile("bundle_gen.go", []byte(output), 0600); err != nil {
		panic(err)
	}
}
